//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ProductoDataAnnotations))]
    public partial class Producto
    {
        public int idProducto { get; set; }
        public string NomProducto { get; set; }
        public string DesProducto { get; set; }
        public Nullable<System.DateTime> FecCreacionP { get; set; }
        public string CodProducto { get; set; }
        public Nullable<decimal> CostoUnitario { get; set; }
    }

    public class ProductoDataAnnotations
    {
        [Required(ErrorMessage = "El {0} es obligatorio")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "El {0} debe tener mínimo {2} y máximo {1} caracteres")]
        [DisplayName("Nombre del Producto")]
        public string NomProducto { get; set; }
        /// <summary>
        /// ////////////////////////
        /// </summary>
        [MaxLength(100, ErrorMessage = "La longitud máxima del {0} es de {1}")]
        [MinLength(3, ErrorMessage = "La longitud mínima del {0} es de {1}")]
        [DisplayName("Descripcion Producto")]
        public string DesProducto { get; set; }
        /// <summary>
        /// ////////////////////////////
        /// </summary>
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> FecCreacionP { get; set; }
        /// <summary>
        /// /////////////////////
        /// </summary>
        [Required(ErrorMessage = "El {0} es obligatorio")]
        public string CodProducto { get; set; }
        public Nullable<decimal> CostoUnitario { get; set; }
    }
}
